create table if not exists public.department_dict (
    id bigint not null primary key generated by default AS IDENTITY,
    name character varying(255) not null
);

-- insert into department_dict (id, name)
-- values
--     (1, 'Главный офис'),
--     (2, 'Южный филиал'),
--     (-1, 'Офис не выбран');

create table if not exists public.employee (
    id bigint not null primary key generated by default AS IDENTITY,
    firstname character varying(255) not null,
    surname character varying(255) not null,
    msisdn character varying(255) not null,
    department_id bigint not null references department_dict(id)
);

-- insert into employee (firstname, surname, msisdn, department_id)
-- values
--     ('Johnny', 'Beard', '79166254226', 1),
--     ('Ma', 'Boy', '78005553535', -1);