

create table if not exists public.employee (
    id bigint not null generated by default AS IDENTITY,
    firstname character varying(255) not null,
    surname character varying(255) not null,
    msisdn character varying(255),
    department_id bigint not null
);

create table if not exists public.department_dict (
   id bigint not null generated by default AS IDENTITY,
   name character varying(255) not null
);